# Generated by Django 5.2.10 on 2026-03-01 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airplane", "0002_alter_airplane_airplane_type_alter_airplane_rows_and_more"),
        ("airport", "0002_alter_route_destination_alter_route_distance_and_more"),
        ("flight", "0002_flight_base_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="airplane.airplane"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="airport.route"
            ),
        ),
    ]
