# Generated by Django 5.2.10 on 2026-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_alter_flight_airplane_alter_flight_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("boarding", "Boarding"),
                    ("departed", "Departed"),
                    ("arrived", "Arrived"),
                    ("cancelled", "Cancelled"),
                    ("delayed", "Delayed"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
