# Generated by Django 5.2.10 on 2026-03-01 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airplane", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="airplane_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="airplane.airplanetype"
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="rows",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="seats_in_row",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
