# Generated by Django 5.2.10 on 2026-03-04 19:04

from django.db import migrations, models

import airplane.models


class Migration(migrations.Migration):

    dependencies = [
        ("airplane",
         "0002_alter_airplane_airplane_type_alter_airplane_rows_and_more"
         ),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airplane.models.airplane_image_path
            ),
        ),
    ]
