# Generated by Django 5.2.10 on 2026-02-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_ticket_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
