# Generated by Django 5.2.10 on 2026-03-01 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_alter_flight_airplane_alter_flight_route"),
        ("order", "0004_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="flight.flight",
            ),
        ),
    ]
