# Generated by Django 5.2.10 on 2026-03-01 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_ticket_flight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="row",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
